# Generated by Django 3.1.4 on 2021-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilwoo', '0002_auto_20210107_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
