# Generated by Django 3.1.4 on 2021-02-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilwoo', '0006_auto_20210201_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='caption2',
            field=models.TextField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='companyimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='caption',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='caption',
            field=models.TextField(),
        ),
    ]
