# Generated by Django 3.1.4 on 2021-02-19 04:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilwoo', '0013_auto_20210215_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='services',
            name='caption2',
        ),
        migrations.AddField(
            model_name='introduction',
            name='location',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='caption',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='caption',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
